### PR TITLE
add viewport to default template

### PR DESCRIPTION
**Pull request by pravdomil**
`charset`, `viewport` and `title` are three minimal tags that should be present in any html5 page?

### CODE REVIEW

**Comment by bebraw** [comment]
LGTM. Any thoughts @sapegin? Maybe we should expand the basic template even more?

**Comment by pravdomil** [comment]
I want to keep it simple and do not load 3rd party template for only one tag which is present in most of pages on the internet.

**Comment by pravdomil** [comment]
you keep it simple for you but not for people using you library, probably everybody will need to that

**Comment by sapegin** [comment]
I don't think your tone is appropriate, so I'm going to close this PR now. Please be more careful with what you're saying next time.

**Pull request closed without merging**
