### PR TITLE
fix: Prevent two rel attributes in the same link tag

### PR DESCRIPTION
**Pull request by bebraw**
Credit: @pldg.

I continued on the work and addressed the comments so we can finally get this one merged.

Closes #12.

### CODE REVIEW

**Comment by bebraw** [comment]
@sapegin Even with the `fix:` prefix it didn't trigger a release though that's following the commit naming convention. Any idea what's up with that?

**Comment by sapegin** [comment]
You can alway check in the log ;-)

```
[semantic-release]: node version >=10.18 is required. Found v9.11.2.
```

**Comment by bebraw** [comment]
Ah, let me bump Node version then. I should have checked Travis. Thanks.

**Pull request merged**
