### PR TITLE
Feature accessibility lang

### PR DESCRIPTION
**Pull request by J-Kallunki**
Accessibility issue with not able to define lang-attribute for html-tag.

### CODE REVIEW

**Comment by J-Kallunki** [comment]
This failure should be not related to PR changes?

**Node.js: 6**
● Test suite failed to run
SecurityError: localStorage is not available for opaque origins

**Comment by bebraw** [comment]
I would say we should just drop Node 6 from the build matrix and set 8 to minimum. I think 6 was deprecated anyway.

**Comment by J-Kallunki** [comment]
Drop node 6 PR: #9

**Comment by J-Kallunki** [comment]
Drop node 6 PR: #9

**Comment by bebraw** [comment]
Thanks, merged. Please rebase.

I thought about the design a bit. Are there other html attributes we should expose? If so, then I would do `htmlAttributes` property or so and let people pass them in within an object that's then serialized to attributes. You would get `htmlAttributes = { lang: 'en', ... }` this way.

Ideally we would be able to validate this with TypeScript (maybe there's a nice type for DOM or something like this?) but that feels like another PR.

**Comment by sapegin** [comment]
Looks good to me! Please update the docs too ;-)

**Comment by J-Kallunki** [comment]
OK I added also to README described as default to `{ lang: 'en' }`
Also included in the custom template part

**Pull request merged**
